project:
  type: website
  output-dir: docs

website:
  title: "Brandon P. Labbree"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv1.qmd
    right:
      - icon: github
        href: https://github.com/blabbree
      - text: "{{< ai osf >}}"
        href: https://osf.io/vztx8/
      - icon: twitter
        href: https://twitter.com/blabbree
      - icon: mastodon
        href: https://tech.lgbt/@blabbree
      - text: Bsky
        href: https://bsky.app/profile/blabbree.bsky.social
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=WuRKHzAAAAAJ&hl=en
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-5893-4469
        

format:
  html:
    # template: jolla 
      # light: Yeti
      # dark: Lux
    css: styles.css
    toc: true


