project:
  type: website
  output-dir: docs

website:
  title: "Brandon P. Labbree"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
    right:
      - icon: github
        href: https://github.com/blabbree
      - icon: twitter
        href: https://twitter.com/blabbree
      - icon: mastodon
        href: https://tech.lgbt/@blabbree
      - text: Bsky
        href: https://bsky.app/profile/blabbree.bsky.social

format:
  html:
    # template: jolla 
      # light: Yeti
      # dark: Lux
    css: styles.css
    toc: true


